In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score,precision_score,accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv("novagen_dataset.csv")

In [3]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [10]:
cols=["Diet_Type__Vegan","Diet_Type__Vegetarian","Blood_Group_B","Blood_Group_O"]
df[cols]=df[cols].astype("int")

In [12]:
df["Blood_Group_AB"]=df["Blood_Group_AB"].astype("int")
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,0,1,1,0,0
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,0,0,1,0,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,1,0,0,0,0
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,1,0,0,1,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,0,1,0,1,0

In [18]:
X=df.drop("Target",axis=1)
y=df["Target"]

In [24]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

rm=RandomForestClassifier(
    n_estimators=200,
    oob_score=True,
    max_depth=4,
    random_state=42
)

rm.fit(X_train,y_train)

RandomForestClassifier(max_depth=4, n_estimators=200, oob_score=True,
                       random_state=42)

In [27]:
y_pred=rm.predict(X_test)
y_train_pred=rm.predict(X_train)
print("precison score is ",precision_score(y_test,y_pred))
print("precison score for training is ",precision_score(y_train,y_train_pred))
print(recall_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

precison score is  0.8237410071942446
precison score for training is  0.8051601423487544
0.906930693069307
0.8481675392670157

In [28]:
from sklearn.ensemble import GradientBoostingClassifier

In [29]:
gbc=GradientBoostingClassifier(
    n_estimators=100,
    random_state=42
)

gbc.fit(X_train,y_train)
y_pred=gbc.predict(X_test)
y_train_pred=gbc.predict(X_train)
print("precison score is ",precision_score(y_test,y_pred))
print("precison score for training is ",precision_score(y_train,y_train_pred))
print(recall_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

precison score is  0.9211045364891519
precison score for training is  0.9164625183733464
0.9247524752475248
0.9183246073298429

In [35]:
#VotingClassifier

from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

lr=LogisticRegression(max_iter=2000)
rfc=RandomForestClassifier()
vc=VotingClassifier(
    estimators=[("lr",lr),("rfc",rfc)]
)

vc.fit(X_train,y_train)
y_pred=vc.predict(X_test)
y_train_pred=vc.predict(X_train)
print("precison score is ",precision_score(y_test,y_pred))
print("precison score for training is ",precision_score(y_train,y_train_pred))
print(recall_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

precison score is  0.9528735632183908
precison score for training is  1.0
0.8207920792079207
0.8837696335078534

In [36]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

svc=SVC()
rfc=RandomForestClassifier()
sc=StackingClassifier(
    estimators=[("svc",svc),("rfc",rfc)],
    final_estimator=LogisticRegression()    
)

sc.fit(X_train,y_train)
y_pred=sc.predict(X_test)
y_train_pred=sc.predict(X_train)
print("precison score is ",precision_score(y_test,y_pred))
print("precison score for training is ",precision_score(y_train,y_train_pred))
print(recall_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

precison score is  0.948051948051948
precison score for training is  1.0
0.9396039603960396
0.9408376963350785