In [17]:
import pandas as pd

In [18]:
df=pd.read_csv("HousePricePrediction.csv")
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [19]:
df["SalePrice"]=df["SalePrice"].fillna(df["SalePrice"].mean())
df["BsmtFinSF2"]=df["BsmtFinSF2"].ffill()
df["TotalBsmtSF"]=df["TotalBsmtSF"].ffill()
df["MSZoning"]=df["MSZoning"].ffill()
df=df.drop(["BldgType","LotConfig","Exterior1st"],axis=1)
df

,Id,MSSubClass,MSZoning,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,5,2003,2003,0.0,856.0,208500.00000
1,1,20,RL,9600,8,1976,1976,0.0,1262.0,181500.00000
2,2,60,RL,11250,5,2001,2002,0.0,920.0,223500.00000
3,3,70,RL,9550,5,1915,1970,0.0,756.0,140000.00000
4,4,60,RL,14260,5,2000,2000,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,7,1970,1970,0.0,546.0,180921.19589
2915,2915,160,RM,1894,5,1970,1970,0.0,546.0,180921.19589
2916,2916,20,RL,20000,7,1960,1996,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,5,1992,1992,0.0,912.0,180921.19589
2918,2918,60,RL,9627,5,1993,1994,0.0,996.0,180921.19589

In [24]:
df=df.drop("MSZoning",axis=1)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   LotArea       2919 non-null   int64
 3   OverallCond   2919 non-null   int64
 4   YearBuilt     2919 non-null   int64
 5   YearRemodAdd  2919 non-null   int64
 6   BsmtFinSF2    2919 non-null   float64
 7   TotalBsmtSF   2919 non-null   float64
 8   SalePrice     2919 non-null   float64
dtypes: float64(3), int64(6)
memory usage: 205.4 KB

In [26]:
X=df.drop("SalePrice",axis=1)
y=df["SalePrice"]

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

In [32]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [33]:
y_pred=model.predict(X_test)

In [34]:
y_pred

array([159830.33829539, 187434.30549799, 164516.35152219, 189626.48723004,
       192222.50812161, 219640.92190751, 140407.68062657, 207334.05720061,
       126737.1619336 , 198910.02245673, 180404.06549653, 196139.19853701,
       167238.75669159, 197433.77265013, 182079.61154049, 186477.36748689,
       162002.00981916, 189695.17063416, 131704.03138728, 162537.07872461,
       195966.2675084 , 133268.7616296 , 134801.87396324, 197084.25368129,
       209662.26152872, 190930.38416071, 183225.55599169, 153186.87393028,
       201813.8345016 , 162684.47582383, 226413.37626424, 159837.91794025,
       194362.88927302, 192306.4487528 , 205310.02787859, 210398.73241475,
       175336.54964918, 168069.65040336, 158193.14520199, 169898.53718428,
       136872.2190693 , 190360.48838554, 221029.78456334, 176221.52075666,
       168702.31500911, 176459.61481085, 203920.20129975, 184292.95997381,
       175172.76829177, 240420.24906112, 154417.54381793, 182761.167474  ,
       141589.27387796, 205554.45072212, 167111.62077234, 133023.72135613,
       159963.62681503, 178228.47980765, 218622.16146991, 170226.66524416,
       167726.60432025, 152516.45322025, 174611.34627259, 164734.56360046,
       170375.01919104, 203757.9751804 , 203240.14456458, 160948.08122241,
       167693.64620427, 166381.99216206, 192846.11446836, 162813.66413734,
       187518.22364777, 219441.18009648, 139742.8904933 , 118278.3686215 ,
       197853.20926882, 139357.33016077, 202896.18980844, 188278.54694362,
       164985.98275799, 198191.16966052, 190701.99183566, 151509.47225514,
       167237.53075995, 186085.64244824, 122911.71685891, 162041.2521112 ,
       141340.0600415 , 174860.87731468, 174562.53004588, 139345.66367305,
       153704.92938408, 228029.48510309, 181328.94707449, 167516.42950337,
       165297.47780194, 200473.06191548, 155750.46439691, 178792.27962264,
       165586.95581177, 177214.78958565, 170381.90106618, 198237.16351494,
       193756.4106172 , 167852.12828161, 143925.58085359, 173300.5434075 ,
       223351.31726489, 182793.11264983, 185324.54397224, 154223.40260496,
       203524.15339543, 247511.33755514, 211003.20959822, 165670.50406813,
       157800.29974102, 206684.23813504, 245434.20140828, 208379.7057112 ,
       155296.27928632, 174532.47517877, 203871.03509655, 156867.1762214 ,
       152676.18767208, 156904.70556182, 174186.11079186, 189013.11520586,
       195869.0897015 , 212082.34590887, 174367.38237875, 144259.47527441,
       199687.47368292, 175390.51820786, 167321.76303418, 170908.18053714,
       203717.89213562, 199571.95129529, 225332.3506718 , 201963.13665991,
       162082.50741457, 172429.59943496, 148786.36383985, 193210.78884365,
       221667.62192929, 218326.15497992, 173701.96378048, 238378.84494737,
       191710.83029283, 196084.137644  , 171879.05894476, 221176.55927717,
       136480.37836328, 168464.51989205, 134026.50971574, 137498.06547989,
       204053.08335785, 210747.78183836, 154773.22715516, 130731.0117164 ,
       226877.10121115, 229935.59534418, 208646.88206333, 169628.8562753 ,
       150373.95892703, 163373.16283497, 226886.14821812, 195868.98554193,
       174300.00917822, 128736.0824789 , 150695.26766386, 156054.49960621,
       192112.44492981, 199121.80922947, 199238.06137505, 212306.3044096 ,
       172038.0346637 , 185127.67147935, 168259.67819205, 200813.92056806,
       214851.89170233, 206154.84432515, 172599.66766461, 196939.03472378,
       194423.6446413 , 198307.23283577, 210740.94455913, 219944.04776847,
       182191.87364945, 166859.97065211, 205120.02418216, 211677.03398574,
       134454.78711964, 154140.87962514, 191373.90192948, 219604.80791056,
       219054.28908195, 184522.01255468, 252041.174865  , 182924.93391712,
       169330.87375017, 180112.77953178, 170221.78996363, 160238.91646974,
       174616.01703965, 106072.72466112, 144941.94770776, 182280.20673226,
       146161.90644273, 175339.94227071, 137312.25494885, 172892.65395884,
       211945.7591777 , 192812.6626938 , 198504.85689629, 136460.98404584,
       198303.40526762, 137070.36739548, 185786.83743504, 183055.96130702,
       131827.87636881, 171276.77685024, 204061.79696368, 116200.98698141,
       219347.18696115, 178714.68715927, 197218.02873272, 199299.39866182,
       148849.06875162, 131438.45393299, 142978.55549824, 160393.82076828,
       155750.45508989, 188567.80684302, 158528.49770689, 176176.47109381,
       162191.92218264, 185352.13594086, 147547.10694621, 147333.89382994,
       219210.72436254, 164640.66226469, 218509.69984527, 219327.66808473,
       235280.22626616, 172896.57443678, 168605.55265933, 197501.34898062,
       191229.23150036, 181491.19338807, 201713.17308349, 164214.17059738,
       173826.21495475, 138345.54123414, 229037.4394108 , 135310.22527834,
       146416.46849371, 164022.77703991, 211542.89635242, 190266.14421188,
       155885.9087322 , 178859.39401909, 154711.78692824, 218022.63686501,
       221264.19046382, 198489.93445981, 179477.34576154, 175193.97272602,
       218358.6157298 , 189944.45304459, 176774.95344893, 149956.69939745,
       178807.42258191, 135754.47545467, 211209.00148034, 191820.83310176,
       165111.50991265, 220686.33141414, 178103.50834981, 181645.29187313,
       221640.43763889, 182489.57579755, 166119.21939888, 145124.08464502,
       224991.7446642 , 167049.89743922, 198689.79799757, 163768.29456461,
       161947.30086261, 149811.67295442, 175408.14112295, 195277.09398922,
       176739.03459887, 197024.71427639, 181319.34866543, 197470.44788738,
       236417.75237778, 150217.22943962, 171873.23543349, 179093.07581891,
       185565.7586527 , 212087.55408834, 179928.50036655, 212908.508069  ,
       153901.65248032, 232157.88109824, 188461.39845331, 215935.44872111,
       164668.52505914, 188274.63356535, 186427.28055822, 166323.46033106,
       182015.93593439, 185884.82404794, 160728.09626461, 176820.40480369,
       141243.75022668, 166737.73360448, 208663.56430857, 162258.87636344,
       179047.27677003, 197829.0357899 , 212245.6017244 , 118840.82652076,
       184089.34125208, 211151.33609774, 187482.4245669 , 178447.68588017,
       115509.40224771, 171529.26792762, 148329.64402319, 200222.69943835,
       128644.76927385, 120342.38728871, 211562.37407379, 159180.75897256,
       219297.89963763, 186626.23464527, 176946.17556231, 175691.14136435,
       147626.57885862, 167528.63286899, 168024.62939174, 178103.39117985,
       186385.51030838, 171749.01552454, 202690.02377345, 140442.25922279,
       180382.7317567 , 126095.84427255, 174018.55288362, 199807.26176763,
       163302.45183063, 204079.80035009, 200693.49904961, 178633.64941159,
       139320.99812746, 188556.84878026, 148295.59829553, 225330.28931351,
       132294.79039734, 192151.23216176, 175004.65316512, 196746.98310487,
       193850.30179295, 178340.12685607, 202750.73966035, 197930.21425177,
       192486.82755116, 182564.04925089, 165856.51342791, 152415.78496404,
       166957.06531784, 139308.40619704, 180966.7114314 , 190035.93338944,
       179846.55630271, 176814.8443837 , 189694.1530172 , 167572.8961803 ,
       170695.20090427, 238827.31470161, 192006.70472456, 177425.60325361,
       138161.17546428, 201308.24645509, 194768.38526395, 165201.1702178 ,
       160203.2978676 , 169150.37728251, 161062.24718382, 206528.00137675,
       199101.42994132, 187873.99684719, 188509.93601239, 155468.57446872,
       194250.50125475, 222218.82997731, 162062.67443809, 177844.29954438,
       169186.22874744, 111901.99672677, 184449.63234611, 176293.17367938,
       158889.52662768, 213989.22088955, 148697.25992133, 192073.63663214,
       188205.0292451 , 146692.89143502, 137521.62206656, 171870.45975654,
       171162.85750657, 204156.16447702, 142398.63575894, 181530.3946359 ,
       182851.26820837, 185564.55146051, 219324.35464311, 227734.83745988,
       194524.18740099, 158646.7151849 , 157467.67953443, 195744.35074714,
       186524.04371688, 202199.39180798, 208942.85325294, 226902.90459384,
       182255.86794746, 190234.94671206, 177641.5748477 , 148249.84911745,
       166569.78813939, 203234.29720308, 175860.90085643, 171155.27994707,
       133512.67799835, 202421.86535587, 158873.71451475, 137087.59134306,
       187510.90183118, 149376.60236852, 162680.2512054 , 225892.70003352,
       180181.60995465, 152659.89231732, 139673.78710408, 204640.92918976,
       183884.06234503, 157861.95680413, 217630.73420462, 161013.89397172,
       184291.5581066 , 188645.57982377, 178357.44535045, 153197.26916343,
       158371.86028689, 160638.50495524, 177948.55403174, 138127.90435788,
       162521.99236517, 191409.14322885, 164939.28413112, 234477.71346533,
       208030.1004096 , 146801.02870389, 174900.25043301, 266082.7310434 ,
       192727.75671713, 155987.93192561, 246472.84814043, 155889.87086133,
       194725.38528564, 205686.70807934, 198804.41974894, 195731.65454846,
       171553.40911136, 224408.30035029, 189466.94225068, 144699.23790105,
       224828.1128422 , 194186.33314863, 154538.88732028, 217665.81500635,
       166692.50979815, 154132.35795076, 174301.36254247, 160539.4883815 ,
       154349.44162352, 197290.48606349, 211990.60921524, 193837.44291916,
       209791.02795618, 198896.90272367, 437044.47804732, 218527.32014225,
       191233.99556646, 209882.16858745, 138608.37076182, 179453.23436603,
       145395.24379426, 207941.02322988, 193952.03487085, 225326.74140367,
       134095.58903652, 192492.09235968, 142210.19901464, 197476.21409107,
       144655.273073  , 151829.21369452, 202837.63741718, 200823.01292561,
       184061.66670931, 180516.43410422, 207305.1275809 , 194096.03858444,
       178664.70039237, 214146.62685251, 170197.69610775, 205147.66574919,
       143350.78177359, 173875.31121197, 182178.09413914, 196396.52289578,
       157241.94929084, 155490.48835197, 221932.32716972, 187992.16988364,
       191792.37763557, 165479.12649354, 138280.30809182, 170472.54277875,
       255014.13095849, 188606.45581639, 199837.87378937, 164767.56307684,
       142286.563693  , 164711.87958294, 213797.37257475, 200871.98620544,
       175140.20183242, 179848.42598374, 181694.48315262, 182131.16581023,
       167657.38602522, 144672.02576242, 182210.55706402, 153612.80916057,
       144088.0392394 , 234783.69611859, 204492.35327485, 201599.5859535 ,
       153646.53091391, 179689.87751616, 230887.90752958, 126013.44219332,
       175281.40371108, 190113.78343475, 163956.96417363, 177960.91210505,
       205712.20399167, 189492.25600815, 168039.39246969, 169912.63037637,
       162536.41268588, 186094.61869527, 125622.3919601 , 154779.77491201,
       170698.29991969, 119290.52108652, 201260.70211085, 203419.51956981,
       150514.30430824, 180380.79564597, 190883.34003651, 168391.22575758,
       173896.6201063 , 194233.86536491, 203438.45621558, 157098.68821527,
       227537.64507514, 236133.67853547, 116739.75302733, 199998.07653596])

In [35]:
y_test

2437    180921.19589
2470    180921.19589
2359    180921.19589
789     187500.00000
1642    180921.19589
            ...
2880    180921.19589
2295    180921.19589
2222    180921.19589
1090     92900.00000
542     213250.00000
Name: SalePrice, Length: 584, dtype: float64

In [36]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_pred)
print(r2)

0.3181453801339049